# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ghorvath <ghorvath@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/31 09:01:03 by ghorvath          #+#    #+#              #
#    Updated: 2021/11/02 08:32:57 by ghorvath         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC		=	gcc	-Wall	-Wextra	-Werror
NAME	=	ft_display_file
SRC		=	display_file.c

all:	$(NAME)

$(NAME):
	$(CC)	$(SRC)	-o	$(NAME)

clean:

fclean:
	/bin/rm	-f	$(NAME)

re:	fclean	all
